

UNASSIGNED_PENDING = 'UPEN'
ASSIGNED_PENDING = 'APEN'
PROCESS = 'PROC'
FINISHED = 'FIN'
WARRANTY = 'WARR'
NO_WARRANTY = 'NO_WARR'

REQUESTED = "REQ"
CONFIRMED = "CONF"
ENDED_UNFINISHED = "END_UNF"



STATE_CHOICES_WORKSHOP = [
    (UNASSIGNED_PENDING, 'UNASSIGNED_PENDING'),
    (ASSIGNED_PENDING, 'ASSIGNED_PENDING'),
    (PROCESS, 'PROCESS'),
    (FINISHED, 'FINISHED'),
    (WARRANTY, 'WARRANTY'),
    (NO_WARRANTY, 'NO_WARRANTY')
]


STATE_CHOICES_ROAD = [
    (REQUESTED, 'REQUESTED'),
    (CONFIRMED, 'CONFIRMED'),
    (UNASSIGNED_PENDING, 'UNASSIGNED_PENDING'),
    (ASSIGNED_PENDING, 'ASSIGNED_PENDING'),
    (ENDED_UNFINISHED, 'ENDED_UNFINISHED'),
    (FINISHED, 'FINISHED'),
    (WARRANTY, 'WARRANTY'),
    (NO_WARRANTY, 'NO_WARRANTY')
]
