# Generated by Django 2.2.9 on 2020-01-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20200121_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='seal_number',
            field=models.CharField(default="SELLO123", max_length=30),
            preserve_default=False,
        ),
    ]
