# Generated by Django 2.2.9 on 2020-01-27 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_service_seal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadservice',
            name='fix',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.Fix'),
        ),
        migrations.AlterField(
            model_name='roadservice',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
