# Generated by Django 2.2.9 on 2020-02-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_auto_20200127_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fix',
            old_name='other_pices',
            new_name='other_pieces',
        ),
        migrations.RenameField(
            model_name='fix',
            old_name='pices',
            new_name='pieces',
        ),
    ]
