# Generated by Django 2.2.9 on 2020-03-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_auto_20200302_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='seal_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
