# Generated by Django 2.2.9 on 2020-03-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_auto_20200318_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpiece',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
