# Generated by Django 2.2.9 on 2020-03-23 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_otherpiece_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.Piece')),
            ],
            options={
                'verbose_name': 'PieceRequest',
                'verbose_name_plural': 'PieceRequests',
            },
        ),
        migrations.CreateModel(
            name='OtherPieceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('otherpiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.OtherPiece')),
            ],
            options={
                'verbose_name': 'OtherPieceRequest',
                'verbose_name_plural': 'OtherPieceRequests',
            },
        ),
    ]
