# Generated by Django 2.2.9 on 2020-03-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_otherpiecerequest_piecerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix',
            name='other_pieces',
            field=models.ManyToManyField(blank=True, to='workshop.OtherPieceRequest'),
        ),
        migrations.AlterField(
            model_name='fix',
            name='pieces',
            field=models.ManyToManyField(blank=True, to='workshop.PieceRequest'),
        ),
    ]
